### ISSUE TITLE
prebuild-install not working when building

### ISSUE THREAD

**Issue by AndreiSoroka** [prebuild/prebuild-install#159]
Hi all!

Same issue: https://github.com/prebuild/prebuild-install/issues/151

I have 
- electon 9.4.4
-  vue-cli-plugin-electron-builder: 2.1.1,

and node addon:

**binding.gyp**:
```gyp
{
  "targets": [
    {
      "target_name": "paste",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ "./paste/paste.cc" ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
      'conditions': [
        [
          'OS=="mac"',
          {
            'cflags+': ['-fvisibility=hidden', '-framework ApplicationServices'],
            'xcode_settings': {
              'GCC_SYMBOLS_PRIVATE_EXTERN': 'YES',
            },
            'link_settings': {
              'libraries': ['-framework ApplicationServices'],
            },
          }
        ],
        [
          "OS=='win'",
           {
             'defines': ['IS_WINDOWS']
           }
        ]
      ]
    }
  ]
}
```

**package.json**
```json
{
  "name": "addons-cpp",
  "version": "1.0.2",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "install": "npm run build",
    "build": "prebuild-install || node-gyp rebuild"
  },
  "author": "",
  "license": "ISC",
  "gypfile": true,
  "dependencies": {
    "node-addon-api": "^4.0.0",
    "prebuild-install": "^6.1.3"
  }
}
```

when I run `vue-cli-service electron:build -mw` I get

```
 INFO  Building app with electron-builder:
  • electron-builder  version=22.11.7 os=20.3.0
  • loaded configuration  file=/Users/andreisoroka/git/other/cpisn-ui/electron-builder.yml
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=addons-cpp@1.0.2 platform=darwin arch=x64
  • install prebuilt binary  name=addons-cpp version=1.0.2 platform=darwin arch=x64 napi=
  • build native dependency from sources  name=addons-cpp
                                          version=1.0.2
                                          platform=darwin
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 6.1.3
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/addons-cpp-v1.0.2-electron-v80-darwin-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/andreisoroka/.npm/_prebuilds/9969f3-addons-cpp-v1.0.2-electron-v80-darwin-x64.tar.gz
    prebuild-install http request GET undefined/releases/download/v1.0.2/addons-cpp-v1.0.2-electron-v80-darwin-x64.tar.gz
    prebuild-install WARN install connect ECONNREFUSED 127.0.0.1:80
    
  • packaging       platform=darwin arch=x64 electron=9.4.4 appOutDir=dist_electron/mac
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
  • building        target=macOS zip arch=x64 file=dist_electron/Recruitment Tools-1.1.3-beta.1-mac.zip
  • building        target=DMG arch=x64 file=dist_electron/Recruitment Tools-1.1.3-beta.1.dmg
  • rebuilding native dependencies  dependencies=addons-cpp@1.0.2 platform=win32 arch=x64
  • install prebuilt binary  name=addons-cpp version=1.0.2 platform=win32 arch=x64 napi=
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 6.1.3
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/addons-cpp-v1.0.2-electron-v80-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/andreisoroka/.npm/_prebuilds/9a5a57-addons-cpp-v1.0.2-electron-v80-win32-x64.tar.gz
    prebuild-install http request GET undefined/releases/download/v1.0.2/addons-cpp-v1.0.2-electron-v80-win32-x64.tar.gz
    prebuild-install WARN install connect ECONNREFUSED 127.0.0.1:80
    
                                    command=/usr/local/bin/node /Users/andreisoroka/git/other/cpisn-ui/node_modules/prebuild-install/bin.js --platform=win32 --arch=x64 --target=9.4.4 --runtime=electron --verbose --force
                                    workingDir=/Users/andreisoroka/git/other/cpisn-ui/node_modules/addons-cpp
ExecError: /Users/andreisoroka/git/other/cpisn-ui/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/andreisoroka/git/other/cpisn-ui/node_modules/builder-util/src/util.ts:249:14)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at ChildProcess.emit (domain.js:470:12)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
```

Where pay attention to

`prebuild-install failed with error` and second same problem `prebuild-install failed with error and build from sources not possible because platform or arch not compatible`

**Comment by vweevers** [comment]
You'll need a Windows machine to compile for Windows, or use prebuilt binaries.

**Comment by AndreiSoroka** [comment]
I see
Thank you.

P.s. how to create prebuilt `addons-cpp-v1.0.2-electron-v80-win32-x64.tar.gz` file?

**Comment by AndreiSoroka** [comment]
Hi!

My solution:

```json
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "install": "npm run build",
    "build": "prebuild-install --runtime=electron --target=13.1.9",
    "prebuild": "prebuild --prerelease --runtime=electron --target=13.1.9"
  },
```
and `npm run prebuild`

P.s. abi node !== abi electron
